spring:
  application:
    name: fhir-auth-client
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: datainterops-fhir-app
            client-secret: nkHVdhNFH8NB32a2wQWKRUBr3s7JYKXy
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/fhir

server:
  port: 9090